// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzgfjevoutbptgsfaioh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Z2ZqZXZvdXRicHRnc2ZhaW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjUzNDUsImV4cCI6MjA3MTQ0MTM0NX0.YN-E-l3qQtHMAhRBNZv5VR0ytBTLawLxdvVMb72ik3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});